name: Deploy Laravel to Hostinger via SFTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          # port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.FTP_PSW }}
          local_path: "./"
          remote_path: "/home/hstgr-linkflow-srv696182/linkflow/"
          sftp_only: true

          # server-dir: linkflow.srv696182.hstgr.cloud/home/hstgr-linkflow-srv696182/
